apiVersion: v1
kind: Service
metadata:
  name: commands-service
  namespace: reactor-space
  labels:
    app: commands
spec:
  type: ClusterIP 
  selector:
    app: commands
  ports:
  # Port 80 for the Service -> targetPort 8083 on the Container
  - port: 8082          # The port other services call (e.g., http://movie-service:80)
    targetPort: 8082  # The actual port the application inside the container listens on
    protocol: TCP
    name: grpc
  # Expose the second port (9090) as well for internal metrics collection
  - port: 8091
    targetPort: 8091
    protocol: TCP
    name: mc