apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: reactor-space
  labels:
    app: db
spec:
  type: ClusterIP 
  selector:
    app: db
  ports:
  # Port 80 for the Service -> targetPort 8083 on the Container
  - port: 8083          # The port other services call (e.g., http://movie-service:80)
    targetPort: 8083  # The actual port the application inside the container listens on
    protocol: TCP
    name: grpc