apiVersion: v1
kind: Service
metadata:
  name: mc-service
  namespace: reactor-space
spec:
  # Type for external traffic via cloud provider Load Balancer
  type: LoadBalancer 
  selector:
    app: mc
  ports:
  # Exposing only the single port needed externally
  - port: 25566 # <--- The port exposed publicly by the Load Balancer
    targetPort: 25566 # <--- The actual port your application container is listening on
    protocol: TCP
    name: conectToGame
  sessionAffinity: None